blog/urls.py
# Author:peter young

from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'blog'

urlpatterns = [
    url(r'^index/$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)$', views.edit_page, name='edit_page'),
    url(r'^edit/action$', views.edit_action, name='edit_action'),
]

blog2/urls.py
# Author:peter young
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^1/$', views.index),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include

# import blog.views as bv

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^blog/', include(('blog.urls','blog'),namespace='blog')),
    url(r'^blog2/', include('blog2.urls')),
]

blog/models.py
from django.db import models


# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=32, default="title")
    context = models.TextField(null=True)
    pub_time = models.DateTimeField(null=True)

    def __str__(self):
        """返回一个对象的描述信息"""
        return self.title

blog2/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

from . import models


def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})


def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


def edit_action(request):
    title = request.POST.get('title','TITLE')
    context = request.POST.get('context','CONTEXT')
    article_id = request.POST.get('article_id','0')
    #print(type(article_id))
    #print(article_id)
    #print(article_id=='0')
    # 对象不存在就创建

    if int(article_id) == 0 :
        print("ok")
        models.Article.objects.create(title=title, context=context)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})

    print("no")
    #存在在原来上面修改
    article = models.Article.objects.get(pk = article_id)
    article.title=title
    article.context = context
    article.save()
    return render(request, 'blog/article_page.html', {'article': article})

blog2/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'blog2/index.html', {'hello': 'hello myblog2'})

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br>
<h3>{{ article.context }}</h3>
<br><br>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="article_id" value="{{ article.id |default:'0'}} "/>
    <label>文章标题
        <input type="text" name="title" value="{{ article.title }}"/>
    </label>
    <br/>
    <label>文章内容
        <input type="text" name="context" value="{{ article.context }}"/>
    </label>
    <br/>
    <input type="submit" value="submit">
</form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1><a href="{% url 'blog:edit_page' 0 %}">新文章</a></h1>
<br>

{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article }}</a>
    <br/><br>
{% endfor %}
</body>
</html>

blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>{{ hello }}</h1>
</body>
</html>